function hypercube = ProcessSnapshot(obj, img, varargin)
% ProcessSnapshot Processes a single raw snapsot image into
% hypercube
%
%   hypercube = ProcessSnapshot(img)

if obj.isReadyForHyper()
    hypercube = hyperspectral.reconstruct_hypercube(...
        img, ...
        obj.coords_xy, ...
        obj.dlambda, ...
        obj.lambda0, ...
        obj.lambda_vector, ...
        obj.sampling, ...
        varargin{:} ...
        );
end
end